/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./src/components/testComponent.vue')['default']
    TodoFilter: typeof import('./src/components/Todos/TodoList/TodoFilter.vue')['default']
    TodoInput: typeof import('./src/components/Todos/TodoInput/TodoInput.vue')['default']
    TodoList: typeof import('./src/components/Todos/TodoList/TodoList.vue')['default']
    TodoListItem: typeof import('./src/components/Todos/TodoList/TodoListItem.vue')['default']
  }
}
